### ISSUE TITLE
Dia 2 - Exercício 7

### ISSUE THREAD

**Issue by villasboas** [matheus-hoy/30-Days-Of-JavaScript#1]
![image](https://user-images.githubusercontent.com/17419545/123098417-81a70b80-d407-11eb-9dd0-985dd0529fd0.png)

Nesse exercicio, voce deveria retirar a frase "Days of Javascript" da frase "30 Days of Javascript" restando somente o "30"

Resultado atual:

![image](https://user-images.githubusercontent.com/17419545/123098633-b5823100-d407-11eb-8224-a6993dc22ad5.png)

**Comment by matheus-hoy** [comment]
resolved in 996ab47
